"""empty message

Revision ID: f4b0e7d1875c
Revises: ab62d1dfeffc
Create Date: 2018-08-09 19:03:59.667459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b0e7d1875c'
down_revision = 'ab62d1dfeffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('amount_ht', sa.Float(), nullable=False),
    sa.Column('amount_ttc', sa.Float(), nullable=False),
    sa.Column('bill_status', sa.Enum('to_pay', 'payed', 'wont_pay', name='billstatus'), nullable=True),
    sa.Column('path_to_bill', sa.Text(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('etablishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablishment_id'], ['etablishment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_entry_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount_ht', sa.Float(), nullable=False),
    sa.Column('amount_ttc', sa.Float(), nullable=False),
    sa.Column('stock_entry_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['stock_entry_id'], ['stock_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_entry_product')
    op.drop_table('stock_entry')
    # ### end Alembic commands ###
